// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from "./core/CancelablePromise"
import { OpenAPI } from "./core/OpenAPI"
import { request as __request } from "./core/request"
import type {
  CoursesCreateCourseData,
  CoursesCreateCourseResponse,
  CoursesReadCoursesData,
  CoursesReadCoursesResponse,
  CoursesReadCourseData,
  CoursesReadCourseResponse,
  CoursesUpdateCourseData,
  CoursesUpdateCourseResponse,
  CoursesDeleteCourseData,
  CoursesDeleteCourseResponse,
  CoursesAttachQuizToCourseData,
  CoursesAttachQuizToCourseResponse,
  CoursesAssignRoleToCourseData,
  CoursesAssignRoleToCourseResponse,
  CoursesRemoveRoleFromCourseData,
  CoursesRemoveRoleFromCourseResponse,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenResponse,
  LoginTestTokenResponse,
  LoginRecoverPasswordData,
  LoginRecoverPasswordResponse,
  LoginResetPasswordData,
  LoginResetPasswordResponse,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentResponse,
  PrivateCreateUserData,
  PrivateCreateUserResponse,
  RolesGetRolesResponse,
  RolesCreateRoleData,
  RolesCreateRoleResponse,
  RolesGetRoleData,
  RolesGetRoleResponse,
  RolesUpdateRoleData,
  RolesUpdateRoleResponse,
  RolesDeleteRoleData,
  RolesDeleteRoleResponse,
  RolesGetUsersByRoleData,
  RolesGetUsersByRoleResponse,
  RolesGetCoursesByRoleData,
  RolesGetCoursesByRoleResponse,
  UsersReadUserMeResponse,
  UsersDeleteUserMeResponse,
  UsersUpdateUserMeData,
  UsersUpdateUserMeResponse,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeResponse,
  UsersReadUsersData,
  UsersReadUsersResponse,
  UsersCreateUserData,
  UsersCreateUserResponse,
  UsersReadUserByIdData,
  UsersReadUserByIdResponse,
  UsersUpdateUserData,
  UsersUpdateUserResponse,
  UsersDeleteUserData,
  UsersDeleteUserResponse,
} from "./types.gen"

export class CoursesService {
  /**
   * Create Course
   * Create a new course. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns CoursePublic Successful Response
   * @throws ApiError
   */
  public static createCourse(
    data: CoursesCreateCourseData,
  ): CancelablePromise<CoursesCreateCourseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/courses/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Courses
   * Retrieve a list of courses. Accessible by any authenticated user.
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns CoursePublic Successful Response
   * @throws ApiError
   */
  public static readCourses(
    data: CoursesReadCoursesData = {},
  ): CancelablePromise<CoursesReadCoursesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/courses/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Course
   * Retrieve a course by its ID. Accessible by any authenticated user.
   * @param data The data for the request.
   * @param data.courseId
   * @returns CourseDetailed Successful Response
   * @throws ApiError
   */
  public static readCourse(
    data: CoursesReadCourseData,
  ): CancelablePromise<CoursesReadCourseResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/courses/{course_id}",
      path: {
        course_id: data.courseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Course
   * Update a course by its ID. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.courseId
   * @param data.requestBody
   * @returns CoursePublic Successful Response
   * @throws ApiError
   */
  public static updateCourse(
    data: CoursesUpdateCourseData,
  ): CancelablePromise<CoursesUpdateCourseResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/courses/{course_id}",
      path: {
        course_id: data.courseId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Course
   * Delete a course by its ID. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.courseId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteCourse(
    data: CoursesDeleteCourseData,
  ): CancelablePromise<CoursesDeleteCourseResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/courses/{course_id}",
      path: {
        course_id: data.courseId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Attach Quiz To Course
   * Attach a quiz to a course. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.courseId
   * @param data.quizId
   * @returns CoursePublic Successful Response
   * @throws ApiError
   */
  public static attachQuizToCourse(
    data: CoursesAttachQuizToCourseData,
  ): CancelablePromise<CoursesAttachQuizToCourseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/courses/{course_id}/attach-quiz",
      path: {
        course_id: data.courseId,
      },
      query: {
        quiz_id: data.quizId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Assign Role To Course
   * Assign a role to a course. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.courseId
   * @param data.roleId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static assignRoleToCourse(
    data: CoursesAssignRoleToCourseData,
  ): CancelablePromise<CoursesAssignRoleToCourseResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/courses/{course_id}/assign-role/{role_id}",
      path: {
        course_id: data.courseId,
        role_id: data.roleId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Remove Role From Course
   * Remove a role from a course. Only accessible by superusers.
   * @param data The data for the request.
   * @param data.courseId
   * @param data.roleId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static removeRoleFromCourse(
    data: CoursesRemoveRoleFromCourseData,
  ): CancelablePromise<CoursesRemoveRoleFromCourseResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/courses/{course_id}/remove-role/{role_id}",
      path: {
        course_id: data.courseId,
        role_id: data.roleId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   * OAuth2 compatible token login, get an access token for future requests
   * @param data The data for the request.
   * @param data.formData
   * @returns Token Successful Response
   * @throws ApiError
   */
  public static loginAccessToken(
    data: LoginLoginAccessTokenData,
  ): CancelablePromise<LoginLoginAccessTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/access-token",
      formData: data.formData,
      mediaType: "application/x-www-form-urlencoded",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Test Token
   * Test access token
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static testToken(): CancelablePromise<LoginTestTokenResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/login/test-token",
    })
  }

  /**
   * Recover Password
   * Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static recoverPassword(
    data: LoginRecoverPasswordData,
  ): CancelablePromise<LoginRecoverPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Reset Password
   * Reset password
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static resetPassword(
    data: LoginResetPasswordData,
  ): CancelablePromise<LoginResetPasswordResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/reset-password/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Recover Password Html Content
   * HTML Content for Password Recovery
   * @param data The data for the request.
   * @param data.email
   * @returns string Successful Response
   * @throws ApiError
   */
  public static recoverPasswordHtmlContent(
    data: LoginRecoverPasswordHtmlContentData,
  ): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/password-recovery-html-content/{email}",
      path: {
        email: data.email,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User
   * Create a new user.
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: PrivateCreateUserData,
  ): CancelablePromise<PrivateCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/private/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class RolesService {
  /**
   * Get Roles
   * @returns RolesPublic Successful Response
   * @throws ApiError
   */
  public static getRoles(): CancelablePromise<RolesGetRolesResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/roles/",
    })
  }

  /**
   * Create Role
   * @param data The data for the request.
   * @param data.requestBody
   * @returns RolePublic Successful Response
   * @throws ApiError
   */
  public static createRole(
    data: RolesCreateRoleData,
  ): CancelablePromise<RolesCreateRoleResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/roles/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Role
   * @param data The data for the request.
   * @param data.roleId
   * @returns RolePublic Successful Response
   * @throws ApiError
   */
  public static getRole(
    data: RolesGetRoleData,
  ): CancelablePromise<RolesGetRoleResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/roles/{role_id}",
      path: {
        role_id: data.roleId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Role
   * @param data The data for the request.
   * @param data.roleId
   * @param data.requestBody
   * @returns RolePublic Successful Response
   * @throws ApiError
   */
  public static updateRole(
    data: RolesUpdateRoleData,
  ): CancelablePromise<RolesUpdateRoleResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/roles/{role_id}",
      path: {
        role_id: data.roleId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete Role
   * @param data The data for the request.
   * @param data.roleId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteRole(
    data: RolesDeleteRoleData,
  ): CancelablePromise<RolesDeleteRoleResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/roles/{role_id}",
      path: {
        role_id: data.roleId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Users By Role
   * @param data The data for the request.
   * @param data.roleId
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static getUsersByRole(
    data: RolesGetUsersByRoleData,
  ): CancelablePromise<RolesGetUsersByRoleResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/roles/{role_id}/users",
      path: {
        role_id: data.roleId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Get Courses By Role
   * @param data The data for the request.
   * @param data.roleId
   * @param data.skip
   * @param data.limit
   * @returns CoursesPublic Successful Response
   * @throws ApiError
   */
  public static getCoursesByRole(
    data: RolesGetCoursesByRoleData,
  ): CancelablePromise<RolesGetCoursesByRoleResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/roles/{role_id}/courses",
      path: {
        role_id: data.roleId,
      },
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}

export class UsersService {
  /**
   * Read User Me
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Delete User Me
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/me",
    })
  }

  /**
   * Update User Me
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUserMe(
    data: UsersUpdateUserMeData,
  ): CancelablePromise<UsersUpdateUserMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update Password Me
   * @param data The data for the request.
   * @param data.requestBody
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static updatePasswordMe(
    data: UsersUpdatePasswordMeData,
  ): CancelablePromise<UsersUpdatePasswordMeResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/me/password",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read Users
   * @param data The data for the request.
   * @param data.skip
   * @param data.limit
   * @returns UsersPublic Successful Response
   * @throws ApiError
   */
  public static readUsers(
    data: UsersReadUsersData = {},
  ): CancelablePromise<UsersReadUsersResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/",
      query: {
        skip: data.skip,
        limit: data.limit,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Create User
   * @param data The data for the request.
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static createUser(
    data: UsersCreateUserData,
  ): CancelablePromise<UsersCreateUserResponse> {
    return __request(OpenAPI, {
      method: "POST",
      url: "/api/v1/users/",
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Read User By Id
   * @param data The data for the request.
   * @param data.userId
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static readUserById(
    data: UsersReadUserByIdData,
  ): CancelablePromise<UsersReadUserByIdResponse> {
    return __request(OpenAPI, {
      method: "GET",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Update User
   * @param data The data for the request.
   * @param data.userId
   * @param data.requestBody
   * @returns UserPublic Successful Response
   * @throws ApiError
   */
  public static updateUser(
    data: UsersUpdateUserData,
  ): CancelablePromise<UsersUpdateUserResponse> {
    return __request(OpenAPI, {
      method: "PATCH",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      body: data.requestBody,
      mediaType: "application/json",
      errors: {
        422: "Validation Error",
      },
    })
  }

  /**
   * Delete User
   * @param data The data for the request.
   * @param data.userId
   * @returns Message Successful Response
   * @throws ApiError
   */
  public static deleteUser(
    data: UsersDeleteUserData,
  ): CancelablePromise<UsersDeleteUserResponse> {
    return __request(OpenAPI, {
      method: "DELETE",
      url: "/api/v1/users/{user_id}",
      path: {
        user_id: data.userId,
      },
      errors: {
        422: "Validation Error",
      },
    })
  }
}
