// This file is auto-generated by @hey-api/openapi-ts

export type Body_courses_update_materials = {
  materials_update: CourseMaterialUpdate
  files?: Array<Blob | File>
}

export type Body_courses_upload_material = {
  file: Blob | File
}

export type Body_login_login_access_token = {
  grant_type?: string | null
  username: string
  password: string
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type CourseAnalyticsPublic = {
  total_users: number
  completed_users: number
  failed_users: number
  average_attempts: number
  average_score: number | null
}

export type CourseCreate = {
  title: string
  description?: string | null
  materials?: Array<string>
  is_active?: boolean
  start_date?: string | null
  end_date?: string | null
}

export type CourseMaterialPublic = {
  course_id: string
  materials: Array<string>
}

export type CourseMaterialUpdate = {
  remove_files?: Array<string>
  new_files?: Array<string>
}

export type CourseProgressPublic = {
  user: UserPublic
  status: CourseStatusEnum
  attempt_count: number
  score: number | null
}

export type CoursePublic = {
  title: string
  description?: string | null
  materials?: Array<string>
  is_active?: boolean
  start_date?: string | null
  end_date?: string | null
  id: string
}

export type CoursesProgressPublic = {
  data: Array<CourseProgressPublic>
  count: number
}

export type CoursesPublic = {
  data: Array<CoursePublic>
  count: number
}

export type CourseStatusEnum = "assigned" | "completed" | "failed"

export const CourseStatusEnum = {
  ASSIGNED: "assigned",
  COMPLETED: "completed",
  FAILED: "failed",
} as const

export type CourseUpdate = {
  title?: string | null
  description?: string | null
  is_active?: boolean | null
  start_date?: string | null
  end_date?: string | null
}

export type HTTPValidationError = {
  detail?: Array<ValidationError>
}

export type Message = {
  message: string
}

export type NewPassword = {
  token: string
  new_password: string
}

export type PrivateUserCreate = {
  email: string
  password: string
  name: string
  is_active?: boolean
  is_superuser?: boolean
}

export type QuizCreate = {
  max_attempts?: number
  passing_threshold?: number
  questions?: Array<QuizQuestion>
  course_id: string | null
}

export type QuizPublic = {
  max_attempts?: number
  passing_threshold?: number
  questions?: Array<QuizQuestion>
  id: string
  course_id: string | null
}

export type QuizQuestion = {
  question: string
  choices: Array<string>
  correct_index: number
}

export type QuizUpdate = {
  max_attempts?: number | null
  passing_threshold?: number | null
  questions?: Array<QuizQuestion> | null
}

export type RoleCreate = {
  name: string
}

export type RolePublic = {
  name: string
  id: string
}

export type RolesPublic = {
  data: Array<RolePublic>
  count: number
}

export type RoleUpdate = {
  name?: string | null
}

export type Token = {
  access_token: string
  token_type?: string
}

export type UpdatePassword = {
  current_password: string
  new_password: string
}

export type UserCreate = {
  name: string
  email: string
  is_active?: boolean
  is_superuser?: boolean
  /**
   * Employee id
   */
  user_id?: string | null
  password: string
  role_id: string | null
}

export type UserPublic = {
  name: string
  email: string
  is_active?: boolean
  is_superuser?: boolean
  /**
   * Employee id
   */
  user_id?: string | null
  id: string
  role_id?: string | null
}

export type UsersPublic = {
  data: Array<UserPublic>
  count: number
}

export type UserUpdate = {
  name?: string | null
  email?: string | null
  user_id?: string | null
  is_active?: boolean | null
  is_superuser?: boolean | null
  role_id?: string | null
}

export type UserUpdateMe = {
  name?: string | null
  email?: string | null
}

export type ValidationError = {
  loc: Array<string | number>
  msg: string
  type: string
}

export type CoursesGetMyCoursesResponse = CoursesPublic

export type CoursesGetCoursesData = {
  limit?: number
  skip?: number
}

export type CoursesGetCoursesResponse = CoursesPublic

export type CoursesCreateCourseData = {
  requestBody: CourseCreate
}

export type CoursesCreateCourseResponse = CoursePublic

export type CoursesGetCourseData = {
  courseId: string
}

export type CoursesGetCourseResponse = CoursePublic

export type CoursesUpdateCourseData = {
  courseId: string
  requestBody: CourseUpdate
}

export type CoursesUpdateCourseResponse = CoursePublic

export type CoursesDeleteCourseData = {
  courseId: string
}

export type CoursesDeleteCourseResponse = Message

export type CoursesGetCourseRolesData = {
  courseId: string
}

export type CoursesGetCourseRolesResponse = RolesPublic

export type CoursesAssignRoleData = {
  courseId: string
  roleId: string
}

export type CoursesAssignRoleResponse = CoursePublic

export type CoursesUnassignRoleData = {
  courseId: string
  roleId: string
}

export type CoursesUnassignRoleResponse = Message

export type CoursesGetCourseUsersData = {
  courseId: string
}

export type CoursesGetCourseUsersResponse = UsersPublic

export type CoursesAssignUserData = {
  courseId: string
  userId: string
}

export type CoursesAssignUserResponse = CoursePublic

export type CoursesUnassignUserData = {
  courseId: string
  userId: string
}

export type CoursesUnassignUserResponse = Message

export type CoursesAttachQuizData = {
  courseId: string
  requestBody: QuizCreate
}

export type CoursesAttachQuizResponse = QuizPublic

export type CoursesGetCourseQuizData = {
  courseId: string
}

export type CoursesGetCourseQuizResponse = QuizPublic

export type CoursesUpdateCourseQuizData = {
  courseId: string
  requestBody: QuizUpdate
}

export type CoursesUpdateCourseQuizResponse = QuizPublic

export type CoursesRemoveCourseQuizData = {
  courseId: string
}

export type CoursesRemoveCourseQuizResponse = Message

export type CoursesGetCourseProgressData = {
  courseId: string
}

export type CoursesGetCourseProgressResponse = CoursesProgressPublic

export type CoursesGetCourseAnalyticsData = {
  courseId: string
}

export type CoursesGetCourseAnalyticsResponse = CourseAnalyticsPublic

export type CoursesUploadMaterialData = {
  courseId: string
  formData: Body_courses_upload_material
}

export type CoursesUploadMaterialResponse = CoursePublic

export type CoursesUpdateMaterialsData = {
  courseId: string
  formData: Body_courses_update_materials
}

export type CoursesUpdateMaterialsResponse = CourseMaterialPublic

export type CoursesListMaterialsData = {
  courseId: string
}

export type CoursesListMaterialsResponse = Array<string>

export type CoursesDownloadMaterialData = {
  filename: string
}

export type CoursesDownloadMaterialResponse = unknown

export type CoursesDeleteMaterialData = {
  courseId: string
  filename: string
}

export type CoursesDeleteMaterialResponse = Message

export type LoginLoginAccessTokenData = {
  formData: Body_login_login_access_token
}

export type LoginLoginAccessTokenResponse = Token

export type LoginTestTokenResponse = UserPublic

export type LoginRecoverPasswordData = {
  email: string
}

export type LoginRecoverPasswordResponse = Message

export type LoginResetPasswordData = {
  requestBody: NewPassword
}

export type LoginResetPasswordResponse = Message

export type LoginRecoverPasswordHtmlContentData = {
  email: string
}

export type LoginRecoverPasswordHtmlContentResponse = string

export type PrivateCreateUserData = {
  requestBody: PrivateUserCreate
}

export type PrivateCreateUserResponse = UserPublic

export type RolesGetRolesResponse = Array<RolePublic>

export type RolesCreateRoleData = {
  requestBody: RoleCreate
}

export type RolesCreateRoleResponse = RolePublic

export type RolesGetRoleData = {
  roleId: string
}

export type RolesGetRoleResponse = RolePublic

export type RolesUpdateRoleData = {
  requestBody: RoleUpdate
  roleId: string
}

export type RolesUpdateRoleResponse = RolePublic

export type RolesDeleteRoleData = {
  roleId: string
}

export type RolesDeleteRoleResponse = Message

export type RolesGetUsersByRoleData = {
  limit?: number
  roleId: string
  skip?: number
}

export type RolesGetUsersByRoleResponse = UsersPublic

export type RolesGetCoursesByRoleData = {
  limit?: number
  roleId: string
  skip?: number
}

export type RolesGetCoursesByRoleResponse = CoursesPublic

export type UsersReadUserMeResponse = UserPublic

export type UsersDeleteUserMeResponse = Message

export type UsersUpdateUserMeData = {
  requestBody: UserUpdateMe
}

export type UsersUpdateUserMeResponse = UserPublic

export type UsersUpdatePasswordMeData = {
  requestBody: UpdatePassword
}

export type UsersUpdatePasswordMeResponse = Message

export type UsersGetUsersData = {
  limit?: number
  skip?: number
}

export type UsersGetUsersResponse = UsersPublic

export type UsersCreateUserData = {
  requestBody: UserCreate
}

export type UsersCreateUserResponse = UserPublic

export type UsersReadUserByIdData = {
  userId: string
}

export type UsersReadUserByIdResponse = UserPublic

export type UsersUpdateUserData = {
  requestBody: UserUpdate
  userId: string
}

export type UsersUpdateUserResponse = UserPublic

export type UsersDeleteUserData = {
  userId: string
}

export type UsersDeleteUserResponse = Message

export type UtilsTestEmailData = {
  emailTo: string
}

export type UtilsTestEmailResponse = Message

export type UtilsHealthCheckResponse = boolean
